import { Field, Float, ID, Int, ObjectType, registerEnumType } from "@nestjs/graphql";
import { PageInfoObject } from "../../graphql/page-info.type";
import { DictionarySenseNarrativeKind, type DictionarySenseNarrativeKind as NarrativeKind, DictionarySenseRecommendationReason, type DictionarySenseRecommendationReason as RecommendationReason } from "../domain/dictionary-lexeme";
registerEnumType(DictionarySenseNarrativeKind, { name: "DictionarySenseNarrativeKind" });
registerEnumType(DictionarySenseRecommendationReason, { name: "DictionarySenseRecommendationReason" });
@ObjectType("DictionaryLanguage") export class DictionaryLanguageObject { @Field(() => ID) id!: string; @Field() code!: string; @Field() name!: string; @Field(() => String, { nullable: true }) defaultScriptCode!: string | null }
@ObjectType("DictionaryLexicalCategory") export class DictionaryLexicalCategoryObject { @Field(() => ID) id!: string; @Field() code!: string; @Field() displayName!: string }
@ObjectType("DictionaryLemma") export class DictionaryLemmaObject { @Field(() => ID) id!: string; @Field() languageTag!: string; @Field() value!: string; @Field() isPrimary!: boolean }
@ObjectType("DictionaryGrammaticalFeature") export class DictionaryGrammaticalFeatureObject { @Field(() => ID) id!: string; @Field() key!: string; @Field() label!: string }
@ObjectType("DictionaryFormRepresentation") export class DictionaryFormRepresentationObject { @Field(() => ID) id!: string; @Field() languageTag!: string; @Field() value!: string }
@ObjectType("DictionaryPronunciation") export class DictionaryPronunciationObject { @Field(() => ID) id!: string; @Field(() => String, { nullable: true }) ipa!: string | null; @Field(() => String, { nullable: true }) audioUrl!: string | null; @Field(() => String, { nullable: true }) dialectTag!: string | null; @Field(() => String, { nullable: true }) syllabification!: string | null }
@ObjectType("DictionaryForm") export class DictionaryFormObject { @Field(() => ID) id!: string; @Field(() => [DictionaryFormRepresentationObject]) representations!: readonly DictionaryFormRepresentationObject[]; @Field(() => [DictionaryGrammaticalFeatureObject]) features!: readonly DictionaryGrammaticalFeatureObject[]; @Field(() => [DictionaryPronunciationObject]) pronunciations!: readonly DictionaryPronunciationObject[] }
@ObjectType("DictionarySenseGloss") export class DictionarySenseGlossObject { @Field(() => ID) id!: string; @Field() languageTag!: string; @Field() text!: string }
@ObjectType("DictionarySenseUsage") export class DictionarySenseUsageObject { @Field(() => ID) id!: string; @Field(() => Float, { nullable: true }) score!: number | null; @Field(() => Int, { nullable: true }) rank!: number | null; @Field(() => String, { nullable: true }) regionTag!: string | null; @Field(() => String, { nullable: true }) register!: string | null; @Field(() => String, { nullable: true }) corpus!: string | null }
@ObjectType("DictionarySynsetDefinition") export class DictionarySynsetDefinitionObject { @Field(() => ID) id!: string; @Field() languageTag!: string; @Field() text!: string }
@ObjectType("DictionarySynset") export class DictionarySynsetObject { @Field(() => ID) id!: string; @Field(() => [DictionarySynsetDefinitionObject]) definitions!: readonly DictionarySynsetDefinitionObject[] }
@ObjectType("DictionarySenseNarrative") export class DictionarySenseNarrativeObject { @Field(() => ID) id!: string; @Field(() => DictionarySenseNarrativeKind) kind!: NarrativeKind; @Field() languageTag!: string; @Field() markdown!: string; @Field(() => String, { nullable: true }) generatedBy!: string | null; @Field(() => String, { nullable: true }) promptVersion!: string | null }
@ObjectType("DictionaryExampleTranslation") export class DictionaryExampleTranslationObject { @Field(() => ID) id!: string; @Field() languageTag!: string; @Field() text!: string; @Field(() => String, { nullable: true }) generatedBy!: string | null }
@ObjectType("DictionaryExample") export class DictionaryExampleObject { @Field(() => ID) id!: string; @Field() languageTag!: string; @Field() text!: string; @Field(() => [DictionaryExampleTranslationObject]) translations!: readonly DictionaryExampleTranslationObject[] }
@ObjectType("DictionarySense") export class DictionarySenseObject { @Field(() => ID) id!: string; @Field(() => Int) order!: number; @Field(() => [DictionarySenseGlossObject]) glosses!: readonly DictionarySenseGlossObject[]; @Field(() => [DictionarySenseUsageObject]) usages!: readonly DictionarySenseUsageObject[]; @Field(() => DictionarySynsetObject, { nullable: true }) synset!: DictionarySynsetObject | null; @Field(() => [DictionarySenseNarrativeObject]) narratives!: readonly DictionarySenseNarrativeObject[]; @Field(() => [DictionaryExampleObject]) examples!: readonly DictionaryExampleObject[] }
@ObjectType("DictionaryLexeme") export class DictionaryLexemeObject { @Field(() => ID) id!: string; @Field() canonicalLemma!: string; @Field(() => DictionaryLanguageObject) language!: DictionaryLanguageObject; @Field(() => DictionaryLexicalCategoryObject) lexicalCategory!: DictionaryLexicalCategoryObject; @Field(() => [DictionaryLemmaObject]) lemmas!: readonly DictionaryLemmaObject[]; @Field(() => [DictionaryFormObject]) forms!: readonly DictionaryFormObject[]; @Field(() => [DictionarySenseObject]) senses!: readonly DictionarySenseObject[] }
@ObjectType("DictionarySenseRecommendation") export class DictionarySenseRecommendationObject { @Field(() => DictionaryLexemeObject) targetLexeme!: DictionaryLexemeObject; @Field(() => DictionarySenseObject) targetSense!: DictionarySenseObject; @Field(() => DictionarySenseRecommendationReason) reason!: RecommendationReason }
@ObjectType("DictionaryLexemeEdge") export class DictionaryLexemeEdgeObject { @Field() cursor!: string; @Field(() => DictionaryLexemeObject) node!: DictionaryLexemeObject }
@ObjectType("DictionaryLexemeConnection") export class DictionaryLexemeConnectionObject { @Field(() => [DictionaryLexemeEdgeObject]) edges!: readonly DictionaryLexemeEdgeObject[]; @Field(() => PageInfoObject) pageInfo!: PageInfoObject; @Field(() => Int) totalCount!: number }
